name: Coverity Scan Automation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  coverity-scan-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Coverity Scan
        uses: synopsys-sig/coverity-scan-action@v2
        with:
          coverity-url: https://scan.coverity.com

          project-name: ${{ github.repository }}

          stream-name: ${{ github.repository }}

          build-command: './gradlew assembleDebug'

          coverity-scan-token: ${{ secrets.COVERITY_SCAN_TOKEN }}
